name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 5.0.1
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.0.0
  chewie: ^1.3.4
  collection: ^1.15.0
  contextmenu: ^3.0.0
  desktop_drop: ^0.3.3
  diacritic: ^0.1.3
  dio: ^5.2.0
  easy_localization: ^3.0.1
  ezanimation: ^0.6.0
  file_picker: ^5.0.1
  file_selector: ^0.9.0
  flutter:
    sdk: flutter 
  flutter_markdown: ^0.6.1
  flutter_portal: ^1.0.0
  flutter_svg: ^2.0.3
  http_parser: ^4.0.0
  image_gallery_saver: ^1.7.0
  image_picker: ^1.0.5
  jiffy: ^5.0.0
  lottie: ^2.7.0
  meta: ^1.3.0
  night_vibes_context_menu:
    path: ../../../night_vibes_context_menu
  path_provider: ^2.0.9
  photo_manager: ^3.0.0-dev.5
  photo_view: ^0.14.0
  rxdart: ^0.27.0
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  stages:
    path: ../../../../stages
  stream_chat_flutter_core: 
    path: ../stream_chat_flutter_core
  synchronized: ^3.0.0
  thumblr: ^0.0.4
  url_launcher: ^6.1.0
  video_player: ^2.6.1
  video_player_macos: ^2.0.1
  video_thumbnail: ^0.5.3
  
dependency_overrides:
  http: ^1.1.2

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  dart_code_metrics: ^4.4.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  mocktail: ^1.0.0
  path: ^1.8.0
