name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 5.0.1
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.0.0
  collection: ^1.15.0
  contextmenu: ^3.0.0
  diacritic: ^0.1.3
  ezanimation: ^0.6.0
  file_picker: ^6.1.1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter 
  flutter_markdown: ^0.6.22
  flutter_portal: ^1.0.0
  flutter_svg: ^2.0.3
 
  http_parser: ^4.0.0
  lottie: ^3.0.0
  meta: ^1.3.0
  night_vibes_context_menu:
    path: ../../../night_vibes_context_menu
  path_provider: ^2.0.9
  photo_view: ^0.14.0
  rxdart: ^0.27.0
  stages:
    path: ../../../../stages
  stream_chat_flutter_core: 
    path: ../stream_chat_flutter_core
  synchronized: ^3.0.0
  thumblr: ^0.0.4
  
dependency_overrides:
  http: ^1.1.2

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  mocktail: ^1.0.0
  path: ^1.8.0
